name: ios_f_n_mathsplashcountbignumbers_3199
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  logger: ^2.5.0
  share_plus: ^10.1.4
  image_picker: ^1.1.2

  # state management
  flutter_bloc: ^9.0.0

  # local data saving
  shared_preferences: ^2.5.2
  freezed_annotation: ^2.4.4
  equatable: ^2.0.7
  just_audio: ^0.9.46
  url_launcher: ^6.3.1
  permission_handler: ^10.4.0
  flutter_native_splash: ^2.4.5
  onesignal_flutter: ^5.1.2
  appsflyer_sdk: ^6.16.21
  http: ^1.2.1
  advertising_id: ^2.0.0
  flutter_inappwebview: ^6.1.5
  external_app_launcher: ^4.0.3
  app_tracking_transparency: ^2.0.6+1
  device_info_plus: ^11.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
    
  flutter_lints: ^4.0.0
  freezed: ^2.5.7
  json_serializable: ^6.9.0
  build_runner: ^2.4.13
  url_launcher: ^6.3.1
  percent_indicator: ^4.2.4
  flutter_timer_countdown: ^1.0.7
  intl: ^0.20.2

flutter:
  uses-material-design: true

  assets:
    - assets/
    - assets/images/
